---
- name: restart kubelet
  service: name=kubelet state=restarted daemon_reload=true

- name: restart containerd
  service: name=containerd state=restarted

- name: restart keepalived
  service: name=keepalived state=restarted